### ISSUE TITLE
Insert a `tikz` figure with its caption in the margin

### ISSUE THREAD

**Issue by artperrin** [sylvain-kern/tufte-style-article#2]
Hi, me again !
This is not really an issue but there is something I would like to do and can not figure out how.

I'm drawing a `tikzpicture` inside a `figure` environment, but the caption I'm setting is displayed below the figure on the left: I would like to have this caption in the right margin, like with the `\textfig` macro.
Here is an illustration of my situation:
![issue](https://user-images.githubusercontent.com/78485334/125964299-e721f836-95a1-490b-92aa-0b668edb7dbc.png)
And the code:
```latex
\documentclass[
    colorful,
]{tufte-style-article}

\usepackage{tikz}
\usepackage{lipsum}
\usetikzlibrary{positioning,fit,calc}
\tikzset{block/.style={draw,thick,text width=2cm,minimum height=1cm,align=center},
         line/.style={-latex}
}

\begin{document}

\lipsum[1]\marginnote{and I'd like the caption of the figure to be written in the margin, like a \inlinecode{latex}{\textfig} would display.}

\begin{figure}[h]
    \centering
    \begin{tikzpicture}[thick,scale=0.8, every node/.style={scale=0.8}]
        \node[block] (a) {bloc a};
        \node[block] (b) at ([xshift=3cm)]a) {bloc b};
        \draw[line] (a.east) -- (b.west);
    \end{tikzpicture}\caption{Caption of the figure}\label{figure_label}
\end{figure}

\end{document}
```

Thanks in advance for your help !

**Comment by sylvain-kern** [comment]
hello king

Actually `\textfig`s and everyting are not floating environmnents, which means the figure and caption are not part of a whole `figure` type environment (this may be an issue to the whole class actually).

My solution to your problem is the following:
```
\documentclass[
    colorful,
]{tufte-style-article}

\usepackage{tikz}
\usepackage{lipsum}
\usetikzlibrary{positioning,fit,calc}
\tikzset{block/.style={draw,thick,text width=2cm,minimum height=1cm,align=center},
         line/.style={-latex}
}

\begin{document}

\lipsum[1]

\medskip
\begin{center}
\marginpar{\captionof{figure}{Caption of the figure}\label{figure_label}}
\begin{tikzpicture}[thick,scale=0.8, every node/.style={scale=0.8}]
    \node[block] (a) {bloc a};
    \node[block] (b) at ([xshift=3cm)]a) {bloc b};
    \draw[line] (a.east) -- (b.west);
\end{tikzpicture}
\end{center}
\medskip

\end{document}
```

The `\marginpar` command needs to be before the figure itself, so its top matches with the top of the figure. `\medskip`s is for manually separating the figure from the surrounding paragraphs since there is no floating environment anymore.

boom
![image](https://user-images.githubusercontent.com/71398822/125966623-dfae73a8-1ce1-41b4-968b-ab885878efdc.png)

**Comment by artperrin** [comment]
Perfect, thanks for the workaround ! 😉
