### ISSUE TITLE
\sidenote and caption overlays

### ISSUE THREAD

**Issue by artperrin** [sylvain-kern/tufte-style-article#3]
Hello my dear friend,

I stumbled across a new issue with margin texts: sometimes the `\sidenote` overlays with a figure's caption in the margin.

![issue](https://user-images.githubusercontent.com/78485334/126766091-28b01876-f3f8-48e8-b234-82c0d04879cb.PNG)

Here is the code of this example:
```latex
\documentclass[colorful]{tufte-style-article}

\usepackage{lipsum}

\begin{document}
    
    \lipsum[1]\sidenote{\lipsum[2]}

    \textfig[.8]{juch.jpg}{The impressive Juch's castle}{label}

\end{document}
```

and the picture can be found [here](https://commons.wikimedia.org/wiki/File:Louis_Le_Guennec_Ch%C3%A2teau_Juch.jpg).

I shall mention that I'm using your last commited class file (commit f1b5a76). Do you happen to have a quickfix or a workaround for this trouble ?

Thanks in advance, and keep on the good work ! 👍

**Comment by sylvain-kern** [comment]
damn bro you keep coming with issues

Glad of your constant interest in this project though. I committed some changes about `\sidenote` in the `.cls`, now it works totally the same as in the `sidenotes` package (plot twist : they're the same macro). The thing is they provide tools to prevent this otherwise inevitable overlapping!

Here is what I came up to fix your issue : 
```latex
\documentclass[colorful]{tufte-style-article}

\usepackage{lipsum}

\begin{document}

    \lipsum[1]\sidenote[][-70pt]{\lipsum[2]}

    \begin{figure}[!htb]
        \sidecaption[][80pt]{The impressive Juch's castle}
        \includegraphics[width=.8\linewidth, outer]{juch.jpg}
    \end{figure}

\end{document}
```

The result : 
![arthu](https://user-images.githubusercontent.com/71398822/126794107-58c007b8-fed8-45c0-9a31-b046d3ed69fc.png)

The `\sidenote` and `\sidecaption` commands have optional parameters, the second is a vertical offset. *The first is the text to be displayed in `\listoffigures` for instance.

Long live Louis Le Guennec.

**Comment by artperrin** [comment]
Hi,
Firstly, I'm using your class for my internship report so yes I find some issues. Hope I'm not upsetting you !

Secondly, I'm quite surprised there are no ways to automate this process tbh: to manually set offset values for each captionned float and building the project again and again seems exhausting... as Lamport says in his book _Latex: A Document Preparation System_ (1994):
> If you spend a lot of time worrying about form, you are missusing Latex.

Anyway, thanks for the workaround !
